services:
  - type: web
    name: fastapi-pdf-parser
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
